# case_manager.py — Case Management + Enterprise PDF generation for SOC Dashboard
import json, os, datetime, textwrap
from fpdf import FPDF

CASES_FILE = os.path.join("logs", "cases.json")


def _load_cases():
    if not os.path.exists(CASES_FILE):
        return []
    try:
        with open(CASES_FILE, "r") as f:
            return json.load(f)
    except (json.JSONDecodeError, IOError):
        return []


def _save_cases(cases):
    os.makedirs(os.path.dirname(CASES_FILE), exist_ok=True)
    with open(CASES_FILE, "w") as f:
        json.dump(cases, f, indent=2, default=str)


def get_cases():
    return _load_cases()


def create_case(title, severity, description, log_index=-1, extra=None):
    cases = _load_cases()
    case = {
        "id": len(cases) + 1,
        "title": title,
        "severity": severity,
        "status": "Open",
        "description": description,
        "log_index": log_index,
        "created_at": datetime.datetime.now(datetime.timezone.utc).isoformat(),
        "updated_at": datetime.datetime.now(datetime.timezone.utc).isoformat(),
    }
    if extra:
        case.update(extra)
    cases.append(case)
    _save_cases(cases)
    return case


def update_case_status(case_id, new_status):
    cases = _load_cases()
    for c in cases:
        if c["id"] == case_id:
            c["status"] = new_status
            c["updated_at"] = datetime.datetime.now(datetime.timezone.utc).isoformat()
            _save_cases(cases)
            return True
    return False


# ═══════════════════════════════════════════════════════════════════════════════
# ENTERPRISE PDF GENERATION
# ═══════════════════════════════════════════════════════════════════════════════

class SOCReport(FPDF):
    """Enterprise-grade SOC Report PDF with structured sections."""

    @staticmethod
    def _safe(text):
        """Sanitize unicode chars unsupported by Helvetica (latin-1 only)."""
        replacements = {
            '\u2014': '-', '\u2013': '-', '\u2018': "'", '\u2019': "'",
            '\u201c': '"', '\u201d': '"', '\u2022': '-', '\u2026': '...',
            '\u2019': "'", '\u00b7': '-', '\u25cf': '*', '\u2192': '->',
            '\u2190': '<-', '\u2713': '[x]', '\u2717': '[!]', '\u00a0': ' ',
        }
        t = str(text)
        for k, v in replacements.items():
            t = t.replace(k, v)
        # Fallback: replace any remaining non-latin-1 chars
        return t.encode('latin-1', errors='replace').decode('latin-1')

    def header(self):
        if self.page_no() == 1:
            return  # Cover page has custom header
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(100, 116, 139)
        self.cell(0, 8, "SecureCorp SOC Console  |  Executive Threat Intelligence Report", align="L")
        self.ln(4)
        self.set_draw_color(30, 41, 59)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(6)

    def footer(self):
        self.set_y(-18)
        self.set_draw_color(30, 41, 59)
        self.line(10, self.get_y(), 200, self.get_y())
        self.set_y(-15)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(100, 116, 139)
        ts = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        self.cell(0, 8, f"Generated by SecureCorp SOC Console  |  {ts}  |  Page {self.page_no()}/{{nb}}", align="C")

    def cover_page(self, total_events=0, environment="Lab"):
        self.add_page()
        self.ln(50)
        # Brand
        self.set_font("Helvetica", "B", 28)
        self.set_text_color(59, 130, 246)
        self.cell(0, 14, "SecureCorp", align="C", ln=True)
        self.set_font("Helvetica", "", 12)
        self.set_text_color(148, 163, 184)
        self.cell(0, 8, "AI-Powered SIEM Platform", align="C", ln=True)
        self.ln(20)
        # Title
        self.set_font("Helvetica", "B", 20)
        self.set_text_color(30, 41, 59)
        self.cell(0, 12, "Executive Threat Intelligence Report", align="C", ln=True)
        self.ln(8)
        # Divider
        self.set_draw_color(59, 130, 246)
        self.set_line_width(0.6)
        self.line(60, self.get_y(), 150, self.get_y())
        self.set_line_width(0.2)
        self.ln(12)
        # Meta
        self.set_font("Helvetica", "", 10)
        self.set_text_color(71, 85, 105)
        ts = datetime.datetime.now().strftime("%B %d, %Y at %H:%M:%S")
        meta = [
            f"Report Date: {ts}",
            f"Environment: {environment}",
            f"Total Events Analyzed: {total_events:,}",
        ]
        for line in meta:
            self.cell(0, 7, line, align="C", ln=True)
        self.ln(25)
        # Confidentiality
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(148, 163, 184)
        self.cell(0, 6, self._safe("CONFIDENTIAL - Internal Use Only"), align="C", ln=True)
        self.cell(0, 6, "This document contains sensitive security intelligence. Do not distribute externally.", align="C", ln=True)

    def section_title(self, title, number=None):
        self._check_page_break(20)
        self.ln(4)
        self.set_font("Helvetica", "B", 12)
        self.set_fill_color(15, 23, 42)
        self.set_text_color(241, 245, 249)
        label = f"  {number}. {title}" if number else f"  {title}"
        self.cell(0, 10, self._safe(label), ln=True, fill=True)
        self.set_text_color(30, 41, 59)
        self.ln(4)

    def sub_heading(self, text):
        self._check_page_break(12)
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(59, 130, 246)
        self.cell(0, 7, self._safe(text), ln=True)
        self.set_text_color(30, 41, 59)
        self.ln(2)

    def body_text(self, text):
        self._check_page_break(10)
        self.set_font("Helvetica", "", 9)
        self.set_text_color(51, 65, 85)
        text_width = self.w - self.l_margin - self.r_margin
        wrapped = textwrap.fill(self._safe(text), width=100)
        self.multi_cell(text_width, 5, wrapped)
        self.ln(2)

    def kv_row(self, key, value):
        self._check_page_break(8)
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(71, 85, 105)
        self.cell(55, 6, self._safe(key + ":"), align="R")
        self.set_font("Helvetica", "", 9)
        self.set_text_color(30, 41, 59)
        val_text = textwrap.shorten(self._safe(value), width=80, placeholder="...")
        self.cell(0, 6, "  " + val_text, ln=True)

    def bullet_list(self, items):
        self.set_font("Helvetica", "", 9)
        self.set_text_color(51, 65, 85)
        indent = 14
        text_width = self.w - self.l_margin - self.r_margin - indent
        if text_width < 20:
            text_width = self.w - self.l_margin - self.r_margin
            indent = 0
        for item in items:
            self._check_page_break(12)
            wrapped = textwrap.fill(self._safe(f"- {item}"), width=90)
            x_start = self.l_margin + indent
            self.set_x(x_start)
            self.multi_cell(text_width, 5, wrapped)
            self.ln(1)

    def metric_table(self, data):
        """Render a 2-column metrics table."""
        self._check_page_break(len(data) * 8 + 10)
        self.set_font("Helvetica", "B", 8)
        self.set_fill_color(30, 41, 59)
        self.set_text_color(241, 245, 249)
        col_w = (self.w - self.l_margin - self.r_margin) / 2
        self.cell(col_w, 7, "  Metric", fill=True)
        self.cell(col_w, 7, "  Value", fill=True, ln=True)
        self.set_text_color(30, 41, 59)
        for i, (k, v) in enumerate(data.items()):
            self.set_font("Helvetica", "", 9)
            if i % 2 == 0:
                self.set_fill_color(241, 245, 249)
            else:
                self.set_fill_color(255, 255, 255)
            self.cell(col_w, 7, self._safe(f"  {k}"), fill=True)
            self.cell(col_w, 7, self._safe(f"  {v}"), fill=True, ln=True)
        self.ln(4)

    def _check_page_break(self, height):
        if self.get_y() + height > self.h - 25:
            self.add_page()


# ─── Single Case PDF ─────────────────────────────────────────────────────────

def generate_case_pdf(case):
    """Generate PDF bytes for a single case."""
    pdf = SOCReport()
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.section_title(f"Case #{case['id']}: {case.get('title', 'Untitled')}")
    pdf.kv_row("Status", case.get("status", "Open"))
    pdf.kv_row("Severity", str(case.get("severity", "N/A")).upper())
    pdf.kv_row("Created", case.get("created_at", ""))
    pdf.kv_row("Updated", case.get("updated_at", ""))
    pdf.ln(4)
    pdf.section_title("Description")
    pdf.body_text(case.get("description", "No description provided."))
    if case.get("threat_type"):
        pdf.section_title("Threat Analysis")
        pdf.kv_row("Threat Type", case.get("threat_type", ""))
        pdf.kv_row("Risk Score", str(case.get("risk_score", "")))
        pdf.kv_row("MITRE Technique", case.get("mitre_technique", ""))
    if case.get("mitigation_steps"):
        pdf.ln(3)
        pdf.section_title("Mitigation Steps")
        pdf.bullet_list(case["mitigation_steps"])
    return bytes(pdf.output())


# ─── Enterprise Executive Report ─────────────────────────────────────────────

def generate_executive_pdf(stats, attack_summary, blocked_ips,
                           mitigations=None, threats=None, top_ips=None):
    """Generate enterprise-grade executive report PDF."""
    pdf = SOCReport()
    pdf.alias_nb_pages()

    total_events = stats.get("Total Events", 0)
    attacks = stats.get("Attacks", stats.get("Total Attacks", 0))
    critical = stats.get("Critical", stats.get("Critical Alerts", 0))
    blocked = stats.get("Blocked IPs", 0)
    unique_attackers = stats.get("Unique Attackers", stats.get("Unique Attacker IPs", 0))
    top_attack = stats.get("Top Attack", stats.get("Top Attack Type", "—"))

    # Risk posture
    if int(critical) >= 5:
        risk_posture = "HIGH"
    elif int(critical) >= 1 or int(attacks) >= 10:
        risk_posture = "MEDIUM"
    else:
        risk_posture = "LOW"

    # ── 1. Cover Page ─────────────────────────────────────────────────────
    pdf.cover_page(total_events=int(total_events), environment="Lab")

    # ── 2. Executive Summary ──────────────────────────────────────────────
    pdf.add_page()
    pdf.section_title("Executive Summary", 1)
    summary = (
        f"During the reporting period, the SecureCorp SOC Console analyzed "
        f"{total_events:,} total events. The system detected {attacks} attack "
        f"events, of which {critical} were classified as critical severity. "
        f"Attacks originated from {unique_attackers} unique source IPs. "
        f"The most frequently observed attack vector was {top_attack}. "
        f"{blocked} IP addresses were automatically blocked by the automated "
        f"response engine. "
        f"Overall risk posture is assessed as {risk_posture}."
    )
    pdf.body_text(summary)

    # ── 3. Key Metrics Overview ───────────────────────────────────────────
    pdf.section_title("Key Metrics Overview", 2)
    pdf.metric_table({
        "Total Events Analyzed": f"{total_events:,}",
        "Attack Events Detected": str(attacks),
        "Critical Alerts": str(critical),
        "Unique Attacker IPs": str(unique_attackers),
        "Blocked IPs": str(blocked),
        "Top Attack Type": str(top_attack),
        "Risk Posture": risk_posture,
    })

    # ── 4. Threat Landscape Analysis ──────────────────────────────────────
    pdf.section_title("Threat Landscape Analysis", 3)

    if attack_summary:
        pdf.sub_heading("Attack Distribution")
        total_atk = sum(attack_summary.values()) or 1
        for atk_type, count in sorted(attack_summary.items(), key=lambda x: -x[1]):
            pct = count / total_atk * 100
            pdf.kv_row(atk_type, f"{count} events ({pct:.1f}%)")
        pdf.ln(3)

    if int(attacks) > 0:
        trend = "increasing" if int(critical) > 2 else "moderate"
        pdf.sub_heading("Threat Trend Assessment")
        pdf.body_text(
            f"Attack activity shows a {trend} trend. The system identified "
            f"{len(attack_summary) if attack_summary else 0} distinct attack types. "
            f"Critical events represent {int(critical)/max(int(attacks),1)*100:.0f}% "
            f"of all detected attacks, indicating "
            f"{'an elevated threat environment requiring immediate attention' if int(critical) > 2 else 'a manageable threat landscape with standard monitoring recommended'}."
        )

    if top_ips:
        pdf.sub_heading("Top Attacker IPs")
        for ip_info in top_ips[:5]:
            if isinstance(ip_info, dict):
                pdf.kv_row(ip_info.get("ip", "?"), f"{ip_info.get('count', 0)} events")
            else:
                pdf.kv_row(str(ip_info), "")

    # ── 5. Detailed AI Threat Analysis ────────────────────────────────────
    if threats:
        pdf.section_title("Detailed AI Threat Analysis", 4)
        for i, t in enumerate(threats[:5], 1):
            pdf.sub_heading(f"Threat {i}: {t.get('threat_type', 'Unknown')}")
            pdf.kv_row("Risk Score", f"{t.get('risk_score', '?')}/100")
            pdf.kv_row("Confidence", f"{t.get('confidence_score', '?')}%")
            pdf.kv_row("Severity", str(t.get("severity", "")).upper())
            if t.get("mitre_technique"):
                pdf.kv_row("MITRE ATT&CK", f"{t['mitre_technique']} — {t.get('mitre_name', '')}")
            if t.get("reasoning"):
                pdf.sub_heading("AI Reasoning")
                pdf.body_text(t["reasoning"])
            if t.get("impact"):
                pdf.sub_heading("Impact Assessment")
                pdf.body_text(t["impact"])
            pdf.ln(3)

    # ── 6. Mitigation & Recommendations ───────────────────────────────────
    sect_num = 5 if threats else 4
    if mitigations:
        steps, recs = mitigations
        if steps or recs:
            pdf.section_title("Mitigation & Recommendations", sect_num)
            if steps:
                pdf.sub_heading("Immediate Mitigation Steps")
                pdf.bullet_list(steps)
                pdf.ln(2)
            if recs:
                pdf.sub_heading("Prevention Recommendations")
                pdf.bullet_list(recs)
            sect_num += 1

    # ── 7. Blocklist / Action Items ───────────────────────────────────────
    if blocked_ips:
        pdf.section_title("Blocklist & Action Items", sect_num)
        pdf.sub_heading(f"Blocked IPs ({len(blocked_ips)})")
        for ip, info in list(blocked_ips.items())[:15]:
            reason = info.get("reason", "") if isinstance(info, dict) else str(info)
            ts = info.get("timestamp", "") if isinstance(info, dict) else ""
            pdf.kv_row(ip, f"{reason}  [{ts[:19]}]" if ts else reason)
        pdf.ln(3)
        pdf.sub_heading("Recommended Actions")
        pdf.bullet_list([
            "Review and confirm all auto-blocked IPs in firewall rules",
            "Escalate critical findings to incident response team",
            "Update SIEM correlation rules based on detected patterns",
            "Schedule follow-up review within 24 hours for high-risk events",
        ])

    return bytes(pdf.output())


# ─── Mitigation Report ───────────────────────────────────────────────────────

def generate_mitigation_pdf(analysis, steps, recs):
    """Generate mitigation-focused PDF bytes."""
    pdf = SOCReport()
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.section_title("Mitigation Report")
    if analysis:
        pdf.kv_row("Threat Type", analysis.get("threat_type", ""))
        pdf.kv_row("Risk Score", str(analysis.get("risk_score", "")))
        pdf.kv_row("Severity", str(analysis.get("severity", "")).upper())
        pdf.kv_row("MITRE", analysis.get("mitre_technique", ""))
        pdf.ln(3)
    if steps:
        pdf.section_title("Mitigation Steps")
        pdf.bullet_list(steps)
        pdf.ln(3)
    if recs:
        pdf.section_title("Prevention Recommendations")
        pdf.bullet_list(recs)
    return bytes(pdf.output())
